name: Mirror Image

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.list.outputs.tags }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
      - id: list
        run: |
          echo "tags=$(go run tools/listdep/main.go)" >> $GITHUB_OUTPUT

  mirror:
    runs-on: ubuntu-latest
    needs:
      - setup
    strategy:
      matrix:
        src: ${{ fromJson(needs.setup.outputs.tags) }}
    permissions:
      contents: read
      packages: write
    steps:
      - id: strip
        run: |
          TAG=${{ matrix.src }}
          echo "dst=${TAG##*/}" >> $GITHUB_OUTPUT
      - uses: docker/login-action@v2
        with:
          registry: public.ecr.aws
          username: ${{ secrets.PROD_ACCESS_KEY_ID }}
          password: ${{ secrets.PROD_SECRET_ACCESS_KEY }}
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: docker.io/${{ matrix.src }}
          dst: |
            public.ecr.aws/supabase/${{ steps.strip.outputs.dst }}
            ghcr.io/supabase/${{ steps.strip.outputs.dst }}
